### PR TITLE
closes #25

### LINKED ISSUE #25: Feature Request: Specify webroot in a variable
I want to serve data generated by another server, using the mounts system of pterodactyl, but mounts cannot include `/home/container` in the path

### PR DESCRIPTION
**Pull request by 404invalid-user**
adds variable to change default config webroot path

### CODE REVIEW

**Comment by finnie2006** [comment]
Not sure why you removed features

**Comment by 404invalid-user** [comment]
its because my ide changed the json formatting and i accidentally edited the default nginx egg as well

**Comment by finnie2006** [comment]
That should be reverted first before merging

**Comment by 404invalid-user** [comment]
I did hence the removed things

**Pull request closed without merging**
